name: release
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:  
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  #pull_request:
    #branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
   runs-on: self-hosted
   permissions:
      id-token: 'write'
      contents: 'read'
   steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.12
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: conjur
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: data/vault/github/gh_cr/username;data/vault/github/gh_cr/password|DEV_PASSWORD
      - name: Validate The Retrieved Secret
        run: |
          if [ "$DEV_PASSWORD" == "asdf" ]; then
            echo "DEV_PASSWORD is correct."
          else
            echo "Error: DEV_PASSWORD is incorrect or not set properly."
            exit 1
          fi
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Workflow
        run: echo ${{ github.workflow }}

